# Generated by Django 4.2 on 2023-04-19 14:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длина')),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Глубина')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Высота')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Хранилище',
                'verbose_name_plural': 'Хранилища',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=50, region=None, verbose_name='Контактный телефон')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Описание')),
                ('feature', models.CharField(blank=True, max_length=100, verbose_name='Особенность')),
                ('temperature', models.IntegerField(blank=True, verbose_name='Температура')),
                ('ceiling_height', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Высота потолка')),
                ('total_storages', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Всего хранилищ')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU', verbose_name='Номер телефона пользователя'),
        ),
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер хранилища')),
                ('rent_start', models.DateTimeField(verbose_name='Дата начала аренды')),
                ('rent_end', models.DateTimeField(verbose_name='Дата окончания аренды')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages_in_use', to='storage.storage', verbose_name='Тип хранилища')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Арендованное хранилище',
                'verbose_name_plural': 'Арендованные ранилища',
            },
        ),
        migrations.AddField(
            model_name='storage',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='storages', to='storage.warehouse', verbose_name='Склады с хранилищами'),
        ),
    ]
