# Generated by Django 4.2 on 2023-04-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storage_warehouse_alter_user_phonenumber_userstorage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Адрес эл. почты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
