# Generated by Django 4.2 on 2023-04-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_storage_height_alter_storage_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorage',
            name='warehouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='storages_in_use', to='storage.warehouse', verbose_name='Склад'),
            preserve_default=False,
        ),
    ]
