# Generated by Django 4.2 on 2023-04-25 13:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_userstorage_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длина')),
                ('width', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Высота')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тип хранилища',
                'verbose_name_plural': 'Типы хранилищ',
            },
        ),
        migrations.AlterModelOptions(
            name='userstorage',
            options={'verbose_name': 'Арендованное хранилище', 'verbose_name_plural': 'Арендованные хранилища'},
        ),
        migrations.RemoveField(
            model_name='storage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='length',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='warehouses',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='width',
        ),
        migrations.RemoveField(
            model_name='userstorage',
            name='number',
        ),
        migrations.RemoveField(
            model_name='userstorage',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='total_storages',
        ),
        migrations.AddField(
            model_name='storage',
            name='floor',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='number',
            field=models.CharField(default=None, max_length=100, verbose_name='Номер хранилища'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='warehouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='storage.warehouse', verbose_name='Склад'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(default=None, max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='storage_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='storage.storagetype', verbose_name='Тип хранилища'),
            preserve_default=False,
        ),
    ]
