# Generated by Django 4.2 on 2023-04-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_user_is_admin'),
        ('storage', '0004_userstorage_warehouse'),
    ]

    operations = [
    ]
