# Generated by Django 4.2 on 2023-04-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_storagetype_alter_userstorage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorage',
            name='storage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rented_storage', to='storage.storage', verbose_name='Хранилище'),
        ),
    ]
