# Generated by Django 4.2 on 2023-04-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_userstorage_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorage',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
